### ISSUE TITLE
More instructions

### ISSUE THREAD

**Issue by silkcom** [gothinkster/golang-gin-realworld-example-app#4]
Right now trying to follow the readme throws several errors.  Including golang.org's x crypto is not found (easy ish fix), going to / returns a 404 which might be expected? and running the tests has several failures.  

It'd be very awesome to have a where to go from here section in your readme and more complete instructions on how to get the backend to startup successfully.

**Comment by silkcom** [comment]
i read the tests wrong, there are several red warnings that tables don't exist from gorm.  The tests do pass

**Comment by wangzitian** [comment]
Thanks for your advices, I will fix errors when I have time. Could you please explain more about `where to go from here section in your readme and more complete instructions`？ R u means more introduction about 3rd tools or packages?

**Comment by dparizek** [comment]
What is easy-ish fix for golang.org's x crypto is not found ?  @silkcom I am total newbie... how do I fix that?

**Comment by wangzitian0** [comment]
Could you plz patse your error info or log?




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            王子田
                            
                            
                                
                                    邮箱：wangzitian0@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
On 04/13/2018 12:03, Dave Parizek wrote: What is easy-ish fix for golang.org's x crypto is not found ?  @silkcom I am total newbie... how do I fix that?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gothinkster/golang-gin-realworld-example-app","title":"gothinkster/golang-gin-realworld-example-app","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gothinkster/golang-gin-realworld-example-app"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dparizek in #4: What is easy-ish fix for golang.org's x crypto is not found ?  @silkcom I am total newbie... how do I fix that?"}],"action":{"name":"View Issue","url":"https://github.com/gothinkster/golang-gin-realworld-example-app/issues/4#issuecomment-381015518"}}}

**Comment by dparizek** [comment]
21:0:08 main        | Build Failed:
 users/models.go:8:2: cannot find package "golang.org/x/crypto/bcrypt" in any of:
	/Users/dave/go/src/gozoca/vendor/golang.org/x/crypto/bcrypt (vendor tree)
	/usr/local/go/src/golang.org/x/crypto/bcrypt (from $GOROOT)
	/Users/dave/go/src/golang.org/x/crypto/bcrypt (from $GOPATH)

**Comment by dparizek** [comment]
hmm... seems right place... https://godoc.org/golang.org/x/crypto/bcrypt

**Comment by wangzitian0** [comment]
https://stackoverflow.com/questions/31334197/failed-to-install-golang-org-x-crypto-bcrypt?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Could this solve your problem?

2018-04-13 12:10 GMT+08:00 Dave Parizek <notifications@github.com>:

**Comment by wangzitian0** [comment]
Was it related to codes? If so, you could give a pr to fixed it. Thanks




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            王子田
                            
                            
                                
                                    邮箱：wangzitian0@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
On 04/13/2018 12:10, Dave Parizek wrote: hmm... seems right place... https://godoc.org/golang.org/x/crypto/bcrypt

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gothinkster/golang-gin-realworld-example-app","title":"gothinkster/golang-gin-realworld-example-app","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gothinkster/golang-gin-realworld-example-app"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dparizek in #4: hmm... seems right place... https://godoc.org/golang.org/x/crypto/bcrypt"}],"action":{"name":"View Issue","url":"https://github.com/gothinkster/golang-gin-realworld-example-app/issues/4#issuecomment-381016555"}}}

**Comment by dparizek** [comment]
I think is an issue with golang... your link gives temp solution of install from github instead... so probably does not warrant a PR / fix - should be fixed at golang.org I think.. not sure

**Comment by wangzitian** [comment]
Never mind, it's a weird issue. You can use this CORS middleware: https://github.com/gin-contrib/cors.

**Comment by wangzitian** [comment]
@dparizek  The depended package was managed by govendor which could be checked in `vendor/vendor.json`. The reason was that I didn't included the package `/x/crypto/bcrypt`, I might install it before this project.  BTW, do you meet the issue silkcom meet ` throws several errors`?
